name: Update Lambda

on:
  push:
    branches:
      - main

jobs:
  update-lambda:
    name: Update Lambda Function
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if needed

      - name: Update Lambda
        run: |
          aws lambda update-function-code --function-name my_function --image-uri <account-id>.dkr.ecr.us-west-2.amazonaws.com/my-repo:latest
